### ISSUE TITLE
Test with CI

### ISSUE THREAD

**Issue by dawsonbotsford** [careercup/CtCI-6th-Edition-JavaScript#8]
Travis or Circle. Would be awesome for **linting** and **unit testing** both. Both options are free for open-source software and provide a much higher code quality for PR's.

**Need to add "dawsonbotsford" to the CarreerCup org** as a [person](https://github.com/orgs/careercup/people) by @gaylemcd or another stake-holder on the careercup GitHub group if I understand the permissions correctly.

**Comment by dawsonbotsford** [comment]
Bump @gaylemcd

**Comment by asaph** [comment]
@dawsonbotsford I enabled Travis CI on this repo.

https://travis-ci.org/careercup/CtCI-6th-Edition-JavaScript

You should be able to push a `.travis.yml` file to the root of this repo to trigger the first build.
